name: Run VK Postcrossing Bot

on:
  schedule:
    - cron: '0 4 * * *' 
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # обязательно! иначе push будет запрещён

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # важно для корректного pull

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          VK_SERVICE_TOKEN: ${{ secrets.VK_SERVICE_TOKEN }}
          VK_COMMUNITY_TOKEN: ${{ secrets.VK_COMMUNITY_TOKEN }}
          USER_ID: ${{ secrets.USER_ID }}
        run: python bot.py

      - name: Commit and push sent_posts.txt if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # подтягиваем актуальную версию main
          git pull origin main

          git add sent_posts.txt

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update sent posts"
            git push origin main
          fi
